---
- hosts: all
  roles:
    - role: trust_my_root_ca
      become: yes

- hosts: lab_hp_proliant_servers
  roles:
    - role: install_proliant_tools
      become: yes

- hosts: proxmox_servers
  roles:
    - role: setup_proxmox
      become: yes

- hosts: lab_apcupsd_slaves:lab_apcupsd_master
  roles:
    - role: setup_apcupsd
      become: yes

- hosts: docker_hosts
  vars:
    docker_users:  # Add ansible user to the docker group so that ansible can further manage docker
     - 'ansible'
    docker_install_compose: true  # Enable Docker Compose installation
  roles:
    - role: geerlingguy.docker
      become: yes

- hosts: all
  roles:
    - role: install-essential-tools
      become: yes
    - role: add_motd
      become: yes
