## Upgrade packages and check basic packages are installed ##

- name: "Upgrade apt packages"
  apt:
    update_cache: yes
    upgrade: yes

- name: "Install basic packages"
  package:
    name: "{{ basic_packages }}"
    state: latest

## Adding my notifications script ##

- name: "Make home bin directory"
  file: 
    path: "/home/{{ username }}/bin"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755 
    state: directory

- name: "Add home bin to PATH"
  copy:
    dest: /etc/profile.d/home-bin-path.sh
    content: "PATH=$PATH:/home/{{ username }}/bin"


- name: "Clone ifttt_message git repo"
  git:
   repo: https://github.com/lriley2020/ifttt_message.git
   dest: "/home/{{ username }}/ifttt_message"
   clone: yes
   update: yes

- name: "Make symlink to ifttt_message script in home bin"
  ansible.builtin.file:
    src: "/home/{{ username }}/ifttt_message/ifttt_message"
    dest: "/home/{{ username }}/bin/ifttt_message"
    owner: "{{ username }}"
    group: "{{  username }}"
    state: link

- name: "Add IFTTT API key as global var"
  ansible.builtin.lineinfile:
    path: "/etc/environment"
    line: 'IFTTT_KEY={{ ifttt_api_key }}'

