## Upgrade packages and check basic packages are installed ##

- name: "Upgrade apt packages"
  apt:
    update_cache: yes
    upgrade: yes

- name: "Install basic packages"
  package:
    name: "{{ basic_packages }}"
    state: latest

## Adding my notifications script ##

- name: "Clone ifttt_message git repo"
  git:
   repo: https://github.com/lriley2020/ifttt_message.git
   dest: "/opt/ifttt_message"
   clone: yes
   update: yes

- name: "Add symlink to ifttt_message script in /usr/local/bin"
  ansible.builtin.file:
    src: "/opt/ifttt_message/ifttt_message"
    dest: "/usr/local/bin/ifttt_message"
    owner: "{{ ansible_user }}"
    group: "{{  ansible_user }}"
    state: link

- name: "Add IFTTT API key file to ifttt_message directory"
  copy:
    dest: "/opt/ifttt_message/ifttt_key"
    content: "{{ ifttt_api_key }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user}}"





