
- name: "Create tmp installation directory"
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: tmpdir

- name: "Download rclone from source"  
  ansible.builtin.get_url:
    url: "{{ rclone_download_server }}/{{ rclone_bin_name }}"
    dest: "{{ tmpdir.path }}/rclone-src.zip"

- name: "Unzip rclone source"
  ansible.builtin.unarchive:
    src: "{{ tmpdir.path }}/rclone-src.zip"
    dest: "{{ tmpdir.path}}"
    remote_src: yes
    list_files: yes
  register: archive_contents

- name: "Copy rclone binary to /usr/bin"
  copy:
    src: "{{tmpdir.path }}/{{archive_contents.files[0].split('/')[0]}}/rclone"
    dest: "/usr/bin/"
    owner: root
    group: root
    remote_src: yes

- name: "Copy rclone man pages"
  copy:
    src: "{{tmpdir.path }}/{{ archive_contents.files[0].split('/')[0] }}/rclone.1"
    dest: "/usr/share/man/man1/"
    owner: root
    group: root
    remote_src: yes

- name: "Remove tmp installation directory"
  ansible.builtin.file:
    path: "{{ tmpdir.path }}"
    state: absent

- name: "Check if rclone is installed correctly"
  command: "which rclone"
  ignore_errors: yes
  register: check_out
