- name: "Setup apcupsd"
  block:
    - name: "Install apcupsd"
      package:
        name: "apcupsd"
        state: latest


    - name: "Edit apccontrol to halt instead of shutdown, and include scripts directory"
      replace: 
        path: /etc/apcupsd/apccontrol
        regexp:  '{{item.From}}'
        replace: '{{item.To}}'
      with_items:
        - { From: '^SCRIPTDIR.*$', To: 'SCRIPTDIR=/etc/apcupsd/action-scripts' }
        - { From: '-h now', To: '-H now' }

    - name: "Copy apcupsd config file to server"
      template:
        src: 'static/etc/apcupsd({{ apcupsd_role }})/apcupsd.conf.j2'
        dest: /etc/apcupsd/apcupsd.conf
        owner: root
        group: root
      register: apcupsd_conf

    - name: "Remove default action scripts"
      file:
        path: '/etc/apcupsd/{{ item }}'
        state: absent
      with_items:
        - "changeme"
        - "commfailure"
        - "commok"
        - "offbattery"
        - "onbattery"

    - name: "Copy apcupsd action scripts"
      copy:
        src: static/etc/apcupsd({{ apcupsd_role }})/action-scripts
        dest: /etc/apcupsd/
        owner: root
        group: root

    - name: "Restart apcupsd"
      ansible.builtin.service:
        name: apcupsd
        state: restarted
        enabled: true
      when:
        apcupsd_conf.changed
  when: apcupsd_role is defined
